### ISSUE TITLE
Do not work with Python 3.5

### ISSUE THREAD

**Issue by gwierzchowski** [jeremychen0127/Json2Xml2Csv#12]
Attempt to run xml2json with Python 3.5 leads to error:
```
Traceback (most recent call last):
  File "python/json2xml2csv/xml_to_json.py", line 5, in <module>
    from xml_to_json_utils import *
  File "/home/grzegorz-ubu/Dokumenty/Projekty/GDMS/json_try/Json2Xml2Csv-master/python/json2xml2csv/xml_to_json_utils.py", line 2, in <module>
    from types import ListType
ImportError: cannot import name 'ListType'
```
It looks like library is not fully ported to Python3.
Note that in Python3 `type` std library changed considerably and there is no more `types.ListType`.
`Programming Language :: Python :: 3*`
specifications should be removed from setup.py
